import type { Metadata } from "next";
import { Protest_Guerrilla, Manrope } from "next/font/google";
import "./globals.css";

const protestGuerrilla = Protest_Guerrilla({
  weight: '400',
  subsets: ["latin"],
});

const manrope = Manrope({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${protestGuerrilla} ${manrope} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
